package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"

	"mc-server-manager/internal/config"
	"mc-server-manager/internal/ui"

	"github.com/spf13/cobra"
)

// serviceTemplate is the canonical systemd unit file embedded in the binary.
// Keeping it here ensures `mc service install` always installs the correct
// version regardless of where the binary is run from.
//
// Design notes:
//   - StartLimitIntervalSec / StartLimitBurst live in [Unit] (systemd ignores
//     them in [Service]).
//   - ExecStart uses /usr/bin/java as a literal path. systemd does NOT expand
//     ${VAR} for the executable (first token) -- only for arguments. On Ubuntu,
//     /usr/bin/java is always managed by update-alternatives and points to the
//     active JDK. Use `sudo update-alternatives --config java` to switch.
//   - ${MC_MIN_MEMORY}, ${MC_MAX_MEMORY}, ${MC_JAR} are argument-position
//     variables and ARE expanded correctly by systemd.
//   - EnvironmentFile=- (leading '-') makes the override file optional.
const serviceTemplate = `[Unit]
Description=Minecraft Server (Fabric)
After=network.target
StartLimitIntervalSec=300
StartLimitBurst=3

[Service]
User=ubuntu
WorkingDirectory=/home/ubuntu/minecraft

# Defaults used when /etc/mc/minecraft.env is absent.
# NOTE: systemd only expands ${VAR} for arguments, not for the executable path,
# so the java binary is hardcoded as /usr/bin/java (managed by update-alternatives).
Environment=MC_JAR=server.jar
Environment=MC_MIN_MEMORY=-Xms2G
Environment=MC_MAX_MEMORY=-Xmx8G

# Optional overrides generated by: sudo mc service generate-env
EnvironmentFile=-/etc/mc/minecraft.env

ExecStart=/usr/bin/java \
    ${MC_MIN_MEMORY} \
    ${MC_MAX_MEMORY} \
    -XX:+UseG1GC \
    -XX:+ParallelRefProcEnabled \
    -XX:MaxGCPauseMillis=200 \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+DisableExplicitGC \
    -XX:+AlwaysPreTouch \
    -XX:G1NewSizePercent=30 \
    -XX:G1MaxNewSizePercent=40 \
    -XX:G1HeapRegionSize=8M \
    -XX:G1ReservePercent=20 \
    -XX:G1MixedGCCountTarget=4 \
    -XX:InitiatingHeapOccupancyPercent=15 \
    -XX:G1MixedGCLiveThresholdPercent=90 \
    -XX:G1RSetUpdatingPauseTimePercent=5 \
    -XX:SurvivorRatio=32 \
    -XX:+PerfDisableSharedMem \
    -XX:MaxTenuringThreshold=1 \
    -Dusing.aikars.flags=https://mcflags.emc.gs \
    -Daikars.new.flags=true \
    -jar ${MC_JAR} --nogui

StandardOutput=journal
StandardError=journal
SyslogIdentifier=minecraft
Restart=on-failure
RestartSec=30
TimeoutStopSec=90
KillSignal=SIGTERM
ProtectSystem=full
ProtectHome=read-only
ReadWritePaths=/home/ubuntu/minecraft
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
`

func newServiceCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "service",
		Short: "Manage the systemd service",
		RunE: func(cmd *cobra.Command, args []string) error {
			return cmd.Help()
		},
	}
	cmd.AddCommand(
		newServiceInstallCmd(),
		newServiceGenerateEnvCmd(),
		newServiceUninstallCmd(),
	)
	return cmd
}

func newServiceInstallCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "install",
		Short: "Install systemd service, environment file, and polkit rule",
		Long: `Install the systemd service unit, generate the JVM environment file
from config.toml, and install a polkit rule so the configured user can
manage the service without sudo/password.`,
		RunE: runServiceInstall,
	}
}

func runServiceInstall(cmd *cobra.Command, args []string) error {
	if os.Getuid() != 0 {
		return fmt.Errorf("this command must be run as root (try: sudo mc service install)")
	}

	// 1. Generate environment file
	fmt.Print(ui.Info("Generating environment file... "))
	envPath := config.DefaultEnvFilePath()
	if err := cfg.GenerateEnvironmentFile(envPath); err != nil {
		fmt.Println(ui.Error("FAILED"))
		return fmt.Errorf("failed to generate environment file: %w", err)
	}
	fmt.Println(ui.Success("OK"))
	fmt.Println(ui.Dim("  " + envPath))

	// 2. Install systemd service (from embedded template)
	fmt.Print(ui.Info("Installing systemd service... "))
	destService := filepath.Join("/etc/systemd/system", cfg.Systemd.Unit)
	if err := os.WriteFile(destService, []byte(serviceTemplate), 0o644); err != nil {
		fmt.Println(ui.Error("FAILED"))
		return fmt.Errorf("writing service file: %w", err)
	}
	fmt.Println(ui.Success("OK"))
	fmt.Println(ui.Dim("  " + destService))

	// 3. Install polkit rule
	fmt.Print(ui.Info("Installing polkit rule... "))
	if err := installPolkitRule(); err != nil {
		fmt.Println(ui.Warning("SKIP"))
		fmt.Println(ui.Dim("  " + err.Error()))
	} else {
		fmt.Println(ui.Success("OK"))
	}

	// 4. Reload systemd
	fmt.Print(ui.Info("Reloading systemd... "))
	reload := exec.Command("systemctl", "daemon-reload")
	if out, err := reload.CombinedOutput(); err != nil {
		fmt.Println(ui.Error("FAILED"))
		return fmt.Errorf("daemon-reload failed: %w\n%s", err, string(out))
	}
	fmt.Println(ui.Success("OK"))

	// 5. Enable service
	fmt.Print(ui.Info("Enabling service... "))
	enable := exec.Command("systemctl", "enable", cfg.Systemd.Unit)
	if out, err := enable.CombinedOutput(); err != nil {
		fmt.Println(ui.Warning("SKIP"))
		fmt.Println(ui.Dim("  " + string(out)))
	} else {
		fmt.Println(ui.Success("OK"))
	}

	fmt.Println()
	fmt.Println(ui.Success("Service installed successfully!"))
	fmt.Println()
	fmt.Println(ui.Dim("The user can now run 'mc start/stop/restart' without sudo."))
	fmt.Println(ui.Dim("If you change memory/java/jar in config.toml, run:"))
	fmt.Println(ui.Dim("  sudo mc service generate-env && mc restart"))

	return nil
}

func newServiceGenerateEnvCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "generate-env",
		Short: "Regenerate /etc/mc/minecraft.env from config.toml",
		Long: `Reads java path, jar name, and memory settings from config.toml
and writes /etc/mc/minecraft.env. The systemd service reads this file at
start-up to override its built-in defaults. Run after changing memory,
java, or jar in config.toml, then restart: mc restart`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if os.Getuid() != 0 {
				return fmt.Errorf("this command must be run as root (try: sudo mc service generate-env)")
			}

			envPath := config.DefaultEnvFilePath()
			if err := cfg.GenerateEnvironmentFile(envPath); err != nil {
				return fmt.Errorf("failed to generate environment file: %w", err)
			}

			fmt.Println(ui.Success("Environment file generated: ") + envPath)
			fmt.Println()
			fmt.Println(ui.FormatKV("Java", cfg.Server.Java))
			fmt.Println(ui.FormatKV("JAR", cfg.Server.Jar))
			fmt.Println(ui.FormatKV("Memory", fmt.Sprintf("%s - %s", cfg.Server.MinMemory, cfg.Server.MaxMemory)))
			fmt.Println()
			fmt.Println(ui.Dim("Restart the server to apply: mc restart"))
			return nil
		},
	}
}

func newServiceUninstallCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "uninstall",
		Short: "Remove systemd service and polkit rule",
		RunE: func(cmd *cobra.Command, args []string) error {
			if os.Getuid() != 0 {
				return fmt.Errorf("this command must be run as root (try: sudo mc service uninstall)")
			}

			exec.Command("systemctl", "stop", cfg.Systemd.Unit).Run()
			exec.Command("systemctl", "disable", cfg.Systemd.Unit).Run()

			servicePath := filepath.Join("/etc/systemd/system", cfg.Systemd.Unit)
			if err := os.Remove(servicePath); err != nil && !os.IsNotExist(err) {
				fmt.Println(ui.Warning("Could not remove service: " + err.Error()))
			} else {
				fmt.Println(ui.Success("Removed: ") + servicePath)
			}

			envPath := config.DefaultEnvFilePath()
			if err := os.Remove(envPath); err != nil && !os.IsNotExist(err) {
				fmt.Println(ui.Warning("Could not remove env file: " + err.Error()))
			} else {
				fmt.Println(ui.Success("Removed: ") + envPath)
			}

			removePolkitRule()

			exec.Command("systemctl", "daemon-reload").Run()
			fmt.Println(ui.Success("Systemd reloaded."))

			fmt.Println()
			fmt.Println(ui.Dim("Config and Minecraft data were NOT removed."))
			return nil
		},
	}
}

func installPolkitRule() error {
	rulesDir := "/etc/polkit-1/rules.d"
	pklaDir := "/etc/polkit-1/localauthority/50-local.d"

	if _, err := os.Stat(filepath.Dir(rulesDir)); err == nil {
		if err := os.MkdirAll(rulesDir, 0o755); err == nil {
			rule := `// Generated by mc-server-manager
polkit.addRule(function(action, subject) {
    if (action.id === "org.freedesktop.systemd1.manage-units" &&
        action.lookup("unit") === "minecraft.service" &&
        subject.user === "ubuntu") {
        return polkit.Result.YES;
    }
});
`
			dest := filepath.Join(rulesDir, "10-mc-minecraft.rules")
			if err := os.WriteFile(dest, []byte(rule), 0o644); err != nil {
				return fmt.Errorf("writing polkit rule: %w", err)
			}
			fmt.Println(ui.Dim("  " + dest))
			return nil
		}
	}

	if runtime.GOOS == "linux" {
		if err := os.MkdirAll(pklaDir, 0o755); err == nil {
			pkla := `[Allow minecraft user to manage minecraft.service]
Identity=unix-user:ubuntu
Action=org.freedesktop.systemd1.manage-units
ResultAny=yes
ResultInactive=yes
ResultActive=yes
`
			dest := filepath.Join(pklaDir, "10-mc-minecraft.pkla")
			if err := os.WriteFile(dest, []byte(pkla), 0o644); err != nil {
				return fmt.Errorf("writing polkit pkla: %w", err)
			}
			fmt.Println(ui.Dim("  " + dest))
			return nil
		}
	}

	return fmt.Errorf("could not find polkit rules directory; configure polkit manually")
}

func removePolkitRule() {
	paths := []string{
		"/etc/polkit-1/rules.d/10-mc-minecraft.rules",
		"/etc/polkit-1/localauthority/50-local.d/10-mc-minecraft.pkla",
	}
	for _, p := range paths {
		if err := os.Remove(p); err == nil {
			fmt.Println(ui.Success("Removed: ") + p)
		}
	}
}
